# Generated by Django 4.0.2 on 2022-02-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=50)),
                ('copies', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
