# Generated by Django 4.0.2 on 2022-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_books_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
