# Generated by Django 4.0.2 on 2022-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_orders_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('order_placed', 'order_placed'), ('dispatched', 'dispatched'), ('cancel', 'cancel'), ('delivered', 'delivered')], default='order_placed', max_length=50),
        ),
    ]
